from pathlib import Path

from docx_text_tools import apply_replacements


DOCS = {
    "reports/summary_report/Grooming_Detection_4_Page_Summary_Report.docx": {
        "Detecting Online Grooming in PASYDA Metadata": "Detecting Online Grooming Patterns in PASYDA Metadata",
        "Four-page research project summary: pair-level modelling, grouped evaluation, and critical analysis": "Four-page project summary: pair-level modelling, grouped testing, and a cautious reading of the results",
        "Page 1: Problem, Dataset, and Task Definition": "Page 1: Problem, Dataset, and Task",
        "This project develops an AI/ML workflow for detecting online grooming on the PASYDA synthetic metadata dataset. The available data contains communication metadata rather than raw message text, with columns for ID, Source, Destination, Date, and Length.": "This project builds a machine-learning workflow for spotting likely online grooming pairs in the PASYDA synthetic metadata dataset. The data does not include message content. It gives only communication metadata: ID, Source, Destination, Date, and Length.",
        "Core methodological decision: The supervised sample is a central-node/contact-node pair, not an individual message row. The solution files identify the true pair in each scenario, not labels for every message.": "The main methodological choice was to treat each central-node/contact-node pair as the supervised sample. This matters because the solution files name the true pair for each scenario; they do not label each message row.",
        "Observed project value": "Value used in the project",
        "Dataset folders": "Dataset folders",
        "5 folders: Dataset-1 to Dataset-5": "5 folders, Dataset-1 to Dataset-5",
        "10 scenarios total, 2 per dataset folder": "10 scenarios in total, with 2 scenarios in each folder",
        "11 central-node/contact-node pairs per scenario": "11 candidate central-node/contact-node pairs in each scenario",
        "1 true grooming-related pair per scenario": "1 true grooming-related pair in each scenario",
        "110 pair-level samples: 10 positive, 100 negative": "110 pair-level samples overall: 10 positive and 100 negative",
        "Hold out one complete dataset folder per fold": "One complete dataset folder held out in each fold",
        "Training directly on raw message rows would be inappropriate because the labels are pair-level labels. Instead, every raw CSV file is used to construct behavioural pair features, and the models are trained on the resulting pair-level table.": "Training on raw message rows would have been the wrong setup, because the labels belong to pairs. I therefore used the raw CSV files to build behavioural features for each candidate pair, then trained the models on the pair-level table.",
        "Page 2: Feature Engineering and Grouped Evaluation": "Page 2: Feature Engineering and Grouped Testing",
        "Feature engineering converted the original metadata into behavioural indicators for each candidate pair. The frozen base table contains pair-level interaction statistics, while the enhanced table adds contextual and sequence-derived features.": "The feature engineering step turned the original metadata into behaviour-based measures for each candidate pair. The frozen base table keeps the core interaction statistics. The enhanced version adds scenario context and simple sequence-based features.",
        "Measure communication intensity and directionality": "Measure how much the pair communicated and who drove the exchange",
        "Capture when and how long interactions occur": "Capture when the interaction happened and how long it lasted",
        "Test whether brevity is predictive": "Check whether shorter messages carry useful signal",
        "Normalize pair behaviour against other candidates": "Compare each pair with the other candidates in the same scenario",
        "Represent interaction rhythm": "Describe how the exchange changed over time",
        "The evaluation used grouped 5-fold testing by dataset folder. Each fold trained on four complete folders and tested on the remaining folder, giving 88 training rows and 22 test rows per fold.": "Evaluation used grouped 5-fold testing by dataset folder. In each fold, the model trained on four full folders and tested on the remaining folder, so every split had 88 training rows and 22 test rows.",
        "Class imbalance handling: The pair-level dataset contains 10 positives and 100 negatives. Random Forest and SVM used balanced class weights; the MLP used positive-class oversampling inside training folds only. Test folds were never oversampled.": "The pair-level dataset is heavily imbalanced, with 10 positives and 100 negatives. Random Forest and SVM used balanced class weights. The MLP used positive-class oversampling, but only inside the training folds. The test folds were left untouched.",
        "Checks whether the true pair is ranked first in each scenario": "Shows whether the true pair was placed first in each scenario",
        "Rewards placing the true pair near the top even when not first": "Gives credit when the true pair is near the top, even if it is not ranked first",
        "Measures false alerts and missed detections at the selected top pair": "Measures false alerts and missed detections for the selected top pair",
        "Evaluate ranking quality under class imbalance": "Evaluate ranking quality when positives are rare",
        "Page 3: Model Comparison and Best Results": "Page 3: Model Comparison and Main Results",
        "Three model families were trained under the same grouped evaluation protocol: Random Forest, RBF-kernel SVM, and a lightweight MLP. The MLP was chosen because the final representation is tabular and the labelled dataset is too small for sequence models such as LSTM or Transformers.": "Three model families were trained under the same grouped evaluation protocol: Random Forest, RBF-kernel SVM, and a small MLP. I used an MLP because the final data is tabular and the labelled dataset is too small to justify sequence models such as LSTMs or Transformers.",
        "Most important interpretation: A single hand-crafted rule, selecting the pair with the shortest average message, achieved the same perfect Top-1 score as the trained full-feature models. This does not mean the models failed; it means PASYDA contains a very strong synthetic signal, so all perfect scores must be interpreted in that context.": "The most important result is also the easiest one to miss: a simple hand-made rule, choosing the pair with the shortest average message, reached the same perfect Top-1 score as the full-feature trained models. That does not make the models useless. It means PASYDA has a very strong synthetic signal, so the perfect scores need to be read carefully.",
        "Hyperparameters were checked using compact nested grouped validation inside each outer training split. Candidate settings for RF depth/leaf size, SVM C values, and MLP hidden sizes/regularisation all retained perfect full-feature test performance, so the final interpretation focuses on robustness rather than chasing higher scores.": "Hyperparameters were checked with compact nested grouped validation inside each outer training split. The tested RF depth and leaf-size settings, SVM C values, and MLP hidden sizes and regularisation values all kept perfect full-feature test performance. For that reason, the interpretation focuses on robustness rather than trying to squeeze out a higher score.",
        "Top-1 mean +/- std": "Top-1 mean +/- std",
        "Best headline result: RF, SVM, and MLP all achieved perfect performance on base and contextual features. The no-length ablation shows that RF and MLP depend partly on length cues, while SVM remains robust.": "Headline result: RF, SVM, and MLP all reached perfect scores with the base and contextual feature sets. The no-length ablation is more revealing: RF and MLP lost some performance when length cues were removed, while SVM stayed stable.",
        "Baseline comparison is also important: highest message count scored 0.00 Top-1, longest duration scored 0.30, but lowest mean length and highest short-message ratio scored 1.00.": "The baselines add useful context. Highest message count scored 0.00 Top-1 and longest duration scored 0.30, while lowest mean length and highest short-message ratio both scored 1.00.",
        "Page 4: Limitations, False Alerts, and Improvements": "Page 4: Limitations, False Alerts, and Next Steps",
        "The project results are strong on PASYDA, but the report should avoid claiming that grooming is solved in real-world settings. The dataset is small, synthetic, and contains only 10 positive pair-level samples.": "The results are strong on PASYDA, but they should not be treated as evidence that grooming detection is solved in real settings. The dataset is synthetic, small, and contains only 10 positive pair-level samples.",
        "Concrete no-length errors were observed: Random Forest missed 3 of 10 true pairs, and MLP missed 1 of 10. The shared difficult case was perp_4 in Dataset-3, where both RF and MLP failed without length-derived cues. This shows why perfect full-feature scores require sceptical interpretation.": "The no-length runs produced concrete errors. Random Forest missed 3 of the 10 true pairs, and the MLP missed 1. The shared difficult case was perp_4 in Dataset-3, where both RF and MLP failed once length-derived cues were removed. This is why the perfect full-feature scores need a sceptical reading.",
        "Further metadata would make the task more realistic and less dependent on synthetic shortcuts. Account age could help identify newly created or throwaway profiles; platform context could distinguish private direct messages from public or group interactions; report status and moderation outcomes could provide stronger weak labels; and longitudinal behavioural annotations could show escalation patterns over time.": "More metadata would make the task more realistic and reduce dependence on synthetic shortcuts. Account age could help identify newly created or throwaway profiles. Platform context could separate private direct messages from public or group activity. Report status and moderation outcomes could provide stronger weak labels, and longitudinal annotations could show whether behaviour escalates over time.",
        "Synthetic shortcut": "Synthetic shortcut",
        "Message-length baselines are perfect, suggesting possible artefacts": "Message-length baselines are perfect, which suggests possible artefacts",
        "Report no-length ablation and validate on external data": "Report the no-length ablation and test on external data",
        "Wrongly flagged pairs could waste investigator time or harm users": "Wrongly flagged pairs could waste investigator time or unfairly affect users",
        "Use human review and calibrated alert thresholds": "Keep human review in the loop and tune alert thresholds",
        "A true harmful pair could be missed": "A genuinely harmful pair could be missed",
        "Use MRR and recall-focused monitoring, not accuracy alone": "Monitor MRR and recall, not accuracy alone",
        "No message content, account age, platform context, or user history": "No message content, account age, platform context, or user history",
        "Collect richer but privacy-aware features": "Collect richer features while protecting privacy",
        "Only 10 positive pair-level samples limits statistical confidence": "Only 10 positive pair-level samples limits confidence in the figures",
        "Use larger labelled datasets and repeated validation": "Use larger labelled datasets and repeat validation",
        "Final conclusion: The proposed pipeline is leakage-safe and performs strongly on PASYDA. However, deployment should be framed as decision support for human review, not automated accusation.": "Final conclusion: the pipeline avoids the main leakage risk and performs strongly on PASYDA. In practice, though, it should be framed as decision support for human review, not as an automated accusation system.",
        "Use complete-folder grouped evaluation for all future experiments.": "Keep using complete-folder grouped evaluation in future experiments.",
        "Keep pair-level modelling because the labels identify pairs, not individual messages.": "Keep pair-level modelling, because the labels identify pairs rather than individual messages.",
        "Include no-length ablation in the final discussion to show critical analysis.": "Include the no-length ablation in the final discussion, because it shows where the perfect scores may be fragile.",
        "Request richer metadata such as conversation platform, account age, temporal history, report status, and validated behavioural annotations.": "Request richer metadata such as platform, account age, temporal history, report status, and validated behavioural annotations.",
        "Treat perfect scores as dataset-specific until tested on independent real-world or semi-realistic data.": "Treat perfect scores as dataset-specific until the method is tested on independent real-world or semi-realistic data.",
    },
    "reports/individual_member_reports/Member_1_Data_EDA_Feature_Engineering_Report.docx": {
        "Individual Contribution Report - Member 1": "Individual Contribution Report - Member 1",
        "Data, EDA, and Feature Engineering Lead | Name: [replace with member name] | Login: [replace]": "Data, EDA, and Feature Engineering Lead | Name: [replace with member name] | Login: [replace]",
        "Project Context": "Project Context",
        "The group project addressed online grooming detection using the PASYDA synthetic metadata dataset. Direct inspection showed that the correct supervised unit was a central-node/contact-node pair rather than a raw message row.": "The group project focused on detecting likely online grooming pairs in the PASYDA synthetic metadata dataset. After checking the files directly, I found that the right supervised unit was a central-node/contact-node pair, not a single raw message row.",
        "Pair-level modelling": "Pair-level modelling",
        "The solution files identify the true pair in each scenario, not labels for individual messages.": "The solution files identify the true pair in each scenario; they do not label individual messages.",
        "Grouped 5-fold evaluation": "Grouped 5-fold evaluation",
        "Each fold holds out one complete dataset folder, avoiding folder-level leakage.": "Each fold holds out one complete dataset folder, which keeps folder-level leakage out of the test set.",
        "Model portfolio": "Model portfolio",
        "Baselines, Random Forest, SVM, and MLP provide meaningful comparison across simple, classical, and deep learning approaches.": "Baselines, Random Forest, SVM, and MLP give a fair comparison between simple rules, classical models, and a small neural model.",
        "Critical analysis": "Critical analysis",
        "No-length ablation and false-alert discussion test whether high scores are robust or shortcut-driven.": "The no-length ablation and false-alert discussion check whether the high scores are robust or partly driven by shortcuts.",
        "Inspected PASYDA folder structure and ignored irrelevant archive artefacts such as __MACOSX.": "I inspected the PASYDA folder structure and filtered out irrelevant archive artefacts such as __MACOSX.",
        "Verified that solution rows were contained in vic_data and vic_data rows were contained in full data files.": "I checked that solution rows were present in vic_data and that vic_data rows were also present in the full data files.",
        "Identified the central node in each scenario and generated 11 candidate contact pairs per scenario.": "I identified the central node in each scenario and generated 11 candidate contact pairs for each one.",
        "Created the modelling-ready pair-level feature table and enhanced contextual feature table.": "I created the modelling-ready pair-level feature table and the enhanced contextual feature table.",
        "Produced EDA plots and report-ready evidence for dataset understanding and feature justification.": "I produced the EDA plots and audit tables used to explain the dataset and justify the feature choices.",
        "Frozen base modelling table with 110 pair-level samples.": "Frozen base modelling table containing 110 pair-level samples.",
        "Enhanced table with contextual ranks, z-scores, and sequence features.": "Enhanced table with contextual ranks, z-scores, and simple sequence features.",
        "EDA visuals and audit tables used to justify modelling decisions.": "EDA visuals and audit tables used to support the modelling decisions.",
        "Reproducible script for deriving contextual features from raw PASYDA files.": "Reproducible script for deriving contextual features from the raw PASYDA files.",
        "Contribution Quality and Academic Value": "Contribution Quality and Academic Value",
        "Main technical contribution: The data work converted many raw PASYDA message rows into the correct 110 pair-level supervised samples. This prevented incorrect message-level labelling and supported a leakage-safe methodology.": "My main technical contribution was converting the raw PASYDA message rows into the correct 110 pair-level supervised samples. This avoided the mistake of treating message rows as labelled examples and gave the project a cleaner evaluation setup.",
        "The feature engineering directly supports the marking criteria because it demonstrates insight beyond raw metadata. The work created behavioural variables for volume, reciprocity, duration, time-of-day activity, short-message behaviour, and scenario-relative ranking.": "The feature engineering also adds academic value because it goes beyond using the raw columns directly. I created behavioural variables for message volume, reciprocity, duration, time-of-day activity, short-message behaviour, and scenario-relative ranking.",
        "Reflection": "Reflection",
        "The most important lesson from this role was that dataset structure must determine the modelling unit. A raw CSV row looked like a natural sample at first, but the labels were actually pair-level. Recognising this avoided a serious methodological flaw.": "The main lesson from this role was that the dataset structure has to decide the modelling unit. At first, a raw CSV row looked like the natural sample. Once I checked the solution files, it became clear that the labels were pair-level, and recognising that avoided a serious methodological error.",
        "Future improvement would include adding richer privacy-aware metadata, such as account age, platform context, reporting history, and longitudinal interaction features.": "If I extended this work, I would add richer privacy-aware metadata, such as account age, platform context, reporting history, and longitudinal interaction features.",
    },
    "reports/individual_member_reports/Member_2_Classical_Machine_Learning_Report.docx": {
        "The group project addressed online grooming detection using the PASYDA synthetic metadata dataset. Direct inspection showed that the correct supervised unit was a central-node/contact-node pair rather than a raw message row.": "The group project focused on detecting likely online grooming pairs in the PASYDA synthetic metadata dataset. Direct inspection of the files showed that the correct supervised unit was a central-node/contact-node pair, not a raw message row.",
        "The solution files identify the true pair in each scenario, not labels for individual messages.": "The solution files identify the true pair in each scenario; they do not label individual messages.",
        "Each fold holds out one complete dataset folder, avoiding folder-level leakage.": "Each fold holds out one complete dataset folder, which avoids folder-level leakage.",
        "Baselines, Random Forest, SVM, and MLP provide meaningful comparison across simple, classical, and deep learning approaches.": "Baselines, Random Forest, SVM, and MLP allow a direct comparison between simple rules, classical models, and a small neural model.",
        "No-length ablation and false-alert discussion test whether high scores are robust or shortcut-driven.": "The no-length ablation and false-alert discussion test whether high scores are robust or partly caused by shortcuts.",
        "Implemented grouped 5-fold evaluation by dataset folder.": "I implemented grouped 5-fold evaluation by dataset folder.",
        "Built heuristic baselines to provide a fair comparison before trained models.": "I built heuristic baselines so the trained models had a clear point of comparison.",
        "Trained and evaluated Random Forest and SVM models using the same folds and metrics.": "I trained and evaluated Random Forest and SVM models using the same folds and metrics.",
        "Ran no-length ablation to test whether model performance depended on message-length artefacts.": "I ran the no-length ablation to check whether performance depended on message-length artefacts.",
        "Recorded Top-1 Accuracy, MRR, Precision, Recall, F1, ROC-AUC, and PR-AUC.": "I recorded Top-1 Accuracy, MRR, Precision, Recall, F1, ROC-AUC, and PR-AUC.",
        "Volume alone failed.": "Volume alone did not identify the true pair.",
        "Very strong but possible artefact.": "Very strong result, but probably tied to the synthetic data pattern.",
        "Perfect full-feature performance.": "Perfect performance with the full feature set.",
        "Performance dropped.": "Performance dropped after length features were removed.",
        "Robust without length features.": "Stayed robust without length features.",
        "Main technical contribution: The evaluation framework avoided leakage by holding out complete dataset folders and treating folds as internal evaluation repeats, not separate experiments.": "My main technical contribution was the evaluation framework. It avoided leakage by holding out complete dataset folders and treating the folds as internal evaluation repeats rather than separate experiments.",
        "The classical ML work strengthened the portfolio by showing that simple baselines, Random Forest, and SVM could be compared under the same protocol. The no-length ablation added critical analysis by testing shortcut dependence rather than reporting perfect scores uncritically.": "The classical ML work strengthened the portfolio because the baselines, Random Forest, and SVM were all compared under the same protocol. The no-length ablation was especially useful because it tested shortcut dependence instead of simply reporting perfect scores.",
        "The main risk in this role was overinterpreting high scores. The baseline and ablation results showed that perfect accuracy can be misleading if a synthetic feature dominates the task.": "The main risk in this role was overinterpreting the high scores. The baseline and ablation results showed that perfect accuracy can be misleading when a synthetic feature dominates the task.",
        "Future work should include systematic hyperparameter search inside training folds only, calibration analysis, and threshold tuning for false-alert control.": "Future work should include systematic hyperparameter search inside the training folds only, calibration analysis, and threshold tuning to control false alerts.",
    },
    "reports/individual_member_reports/Member_3_Deep_Learning_Integration_Report.docx": {
        "The group project addressed online grooming detection using the PASYDA synthetic metadata dataset. Direct inspection showed that the correct supervised unit was a central-node/contact-node pair rather than a raw message row.": "The group project focused on detecting likely online grooming pairs in the PASYDA synthetic metadata dataset. Checking the dataset structure showed that the supervised unit had to be a central-node/contact-node pair, not a raw message row.",
        "The solution files identify the true pair in each scenario, not labels for individual messages.": "The solution files identify the true pair in each scenario; they do not label individual messages.",
        "Each fold holds out one complete dataset folder, avoiding folder-level leakage.": "Each fold holds out one complete dataset folder, which reduces the risk of folder-level leakage.",
        "Baselines, Random Forest, SVM, and MLP provide meaningful comparison across simple, classical, and deep learning approaches.": "Baselines, Random Forest, SVM, and MLP give a useful comparison between simple rules, classical models, and a small neural model.",
        "No-length ablation and false-alert discussion test whether high scores are robust or shortcut-driven.": "The no-length ablation and false-alert discussion test whether the high scores are robust or partly shortcut-driven.",
        "Selected a small MLP as the deep learning model because the final data representation is tabular and small.": "I selected a small MLP as the deep learning model because the final representation is small and tabular.",
        "Trained the MLP using the same grouped folds as the classical models.": "I trained the MLP using the same grouped folds as the classical models.",
        "Compared MLP results against Random Forest, SVM, and heuristic baselines.": "I compared the MLP results against Random Forest, SVM, and the heuristic baselines.",
        "Integrated model comparison, ablation findings, false-alert discussion, and limitations into final report materials.": "I brought the model comparison, ablation findings, false-alert discussion, and limitations together in the final report materials.",
        "Prepared the 4-page summary report and experiment portfolio structure.": "I prepared the four-page summary report and organised the experiment portfolio structure.",
        "Perfect on base features.": "Perfect score on the base features.",
        "Perfect on enhanced features.": "Perfect score on the enhanced features.",
        "Small drop after ablation.": "Small drop after removing length features.",
        "Best robustness result.": "Best robustness result in the ablation.",
        "Main technical contribution: The integration work connected the deep learning experiment to the wider evidence base, explaining why an MLP was more appropriate than LSTM, GRU, or Transformer models for this small tabular dataset.": "My main technical contribution was connecting the deep learning experiment to the rest of the evidence. I also explained why an MLP made more sense than an LSTM, GRU, or Transformer for this small tabular dataset.",
        "The final integration focused on critical interpretation rather than only reporting accuracy. This included discussion of false positives, false negatives, synthetic-data artefacts, and human-in-the-loop deployment.": "The final integration focused on interpretation, not just accuracy. It covered false positives, false negatives, synthetic-data artefacts, and the need for human review before any real-world use.",
        "The main lesson from the deep learning role was that model complexity must match data structure. A sequence model would look more advanced, but it would be poorly justified because the labels and feature table are pair-level and tabular.": "The main lesson from the deep learning role was that model complexity has to match the data. A sequence model would look more advanced, but it would be poorly justified because the labels and feature table are pair-level and tabular.",
        "Future work should test the MLP on larger, externally validated datasets and include calibration analysis so scores can support risk ranking rather than automated accusation.": "Future work should test the MLP on larger externally validated datasets and include calibration analysis, so scores can support risk ranking rather than automated accusation.",
    },
    "reports/submission_front_matter/Cover_Page_COMP7029_Grooming_Detection.docx": {
        "Online Grooming Detection using PASYDA Metadata": "Online Grooming Detection Using PASYDA Metadata",
        "PASYDA synthetic online grooming metadata dataset": "PASYDA synthetic online grooming metadata dataset",
        "Submitted documents include the cover page, experiment index, portfolio of experiment reports, four-page summary report, and supporting individual contribution reports where required.": "This submission includes the cover page, experiment index, portfolio of experiment reports, four-page summary report, and supporting individual contribution reports where required.",
    },
    "reports/submission_front_matter/Generative_AI_Use_Disclosure.docx": {
        "Generative AI Use Disclosure": "Generative AI Use Disclosure",
        "Generative AI tools were used to support project planning, code structuring, report drafting, wording refinement, and critical review of the methodology and interpretation.": "Generative AI tools were used during the project for planning support, code organisation, early report drafting, wording checks, and review of the methodology and interpretation.",
        "The team remained responsible for reviewing the generated content, validating the methodology, checking outputs, interpreting the results, and deciding what to include in the final submission.": "The team remained responsible for checking the material, validating the methodology, reviewing outputs, interpreting the results, and deciding what belonged in the final submission.",
        "Use of AI included support for:": "The support included:",
        "summarising the assignment requirements and marking criteria": "summarising the assignment requirements and marking criteria",
        "structuring the pair-level modelling workflow": "structuring the pair-level modelling workflow",
        "drafting Python scripts for feature engineering, grouped evaluation, tuning analysis, and report generation": "drafting Python scripts for feature engineering, grouped evaluation, tuning analysis, and report generation",
        "drafting and refining report wording": "drafting and refining report wording",
        "identifying limitations, false-positive/false-negative risks, and synthetic-data shortcut concerns": "identifying limitations, false-positive and false-negative risks, and possible synthetic-data shortcuts",
        "No AI-generated output was submitted without human review. The final interpretation acknowledges that the PASYDA dataset is synthetic and that perfect scores must be treated cautiously.": "No generated material was included without human review. The final interpretation also makes clear that PASYDA is synthetic and that the perfect scores should be treated cautiously.",
        "This disclosure should be checked against the latest University of Kent Generative AI assessment guidance before final submission.": "This disclosure should be checked against the latest University of Kent guidance on generative AI before submission.",
    },
}


def output_path(path):
    path = Path(path)
    return path.with_name(f"{path.stem}_humanized{path.suffix}")


def main():
    for src, replacements in DOCS.items():
        dst = output_path(src)
        apply_replacements(src, dst, replacements)
        print(dst)


if __name__ == "__main__":
    main()
